# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7aeb5558526df2c95a807c80ac5b2449"
application_url = "https://guidelines-bob-sender-severe.trycloudflare.com"
embedded = true
name = "app-shopi-AI"
handle = "app-shopi-ai"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://guidelines-bob-sender-severe.trycloudflare.com/auth/callback",
  "https://guidelines-bob-sender-severe.trycloudflare.com/auth/shopify/callback",
  "https://guidelines-bob-sender-severe.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-a8d4ad92.myshopify.com"
automatically_update_urls_on_dev = true
